apiVersion: v1
kind: Service
metadata:
    name: svc-azuredevopsapistag
    labels:
        product: azuredevopsapistag
spec:
    selector:
        app: app-azuredevopsapistag
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: dep-azuredevopsapistag
spec:
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: app-azuredevopsapistag
        spec:
            containers:
            - image: demambo.azurecr.io/azuredevopsapi:__Build.BuildId__
              imagePullPolicy: IfNotPresent
              name: azuredevopsapistag
              ports:
              - containerPort: 80
              env:
              - name: ASPNETCORE_ENVIRONMENT
                value: "Staging"
            imagePullSecrets:
            - name: regsecret
